spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bunbun
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      dialect:
      ddl-auto: update
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true
